language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"

jobs:
  include:
    - stage: test
      name: Run test suites
      install:
        - cd test-assignment-seulminryu
      script:
        - npm test
      name: Run test suites 2
      install:
        - cd test-assignment-zhonghengsun
      script:
        - npm test
    - stage: build
      name: Build client
      install:
        - cd client
      script:
        - npm run build
    - stage: build
      name: Build server
      install:
        - cd web-api-auth-examples/authorization_code
      script:
        - node app.js
notifications:
  email: false