language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"
before_install: cd test-assignment-zhonghengsun
script:
  - npm run test
branches:
  only:
    - master
    - spike/43/setting-up-travis-ci-sun
